# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "H月姬H"
subtitle: "Meitsuki的涩涩资源"
description: "人人都爱美少女"
keywords: "galgame, erogame, 美少女游戏, 视觉小说, 恋爱, 轻小说, 文字冒险, 恋爱养成, 工口, Visual Novel"
author: "Meitsuki"
language: "zh-CN"
timezone: "Asia/Shanghai"

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://gal.mikuhitori.xyz
permalink: p/:abbrlink/
permalink_defaults:
  lang: zh-CN
pretty_urls:
  trailing_index: false # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: false # Set to false to remove trailing '.html' from permalinks

# abbrlink config
abbrlink:
  alg: crc16 #support crc16(default) and crc32
  rep: dec #support dec(default) and hex
  drafts: false #(true)Process draft,(false)Do not process draft. false(default)
  # Generate categories from directory-tree
  # depth: the max_depth of directory-tree you want to generate, should > 0
  auto_category:
    enable: true #true(default)
    depth: #3(default)
    over_write: false
  auto_title: false #enable auto title, it can auto fill the title by path
  auto_date: false #enable auto date, it can auto fill the date by time today
  force: false #enable force mode,in this mode, the plugin will ignore the cache, and calc the abbrlink for every post even it already had abbrlink. This only updates abbrlink rather than other front variables.

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
# 指定不渲染某些页面
skip_render:
  - README.md
  - CODE_OF_CONDUCT.md
  - google5e9998f4937b96cc.html

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
syntax_highlighter: highlight.js
highlight:
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 8
  order_by: -updated

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
  - "_redirects"
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  - type: git
    repository: git@github.com:Meitsuki233/gal.git
    branch: main
  - type: cjh_google_url_submitter
  - type: cjh_bing_url_submitter
  - type: cjh_baidu_url_submitter

tag_generator:
  enable_index_page: false

search:
  path: search.json
  field: post
  content: true
  format: striptags

feed:
  enable: true
  type:
    - atom
    - rss2
  path:
    - atom.xml
    - rss2.xml
  limit: 0
  hub:
  content: true
  content_limit: 140
  content_limit_delim: " "
  order_by: -date
  icon: icon.png
  autodiscovery: true
  template:

nofollow:
  enable: true
  field: site
  exclude:

sitemap:
  path:
    - sitemap.xml
    - sitemap.txt
  template: ./sitemap.xml
  template_txt: ./sitemap.txt
  rel: false
  tags: true
  categories: true

baidusitemap:
  path: baidusitemap.xml

markdown_it_plus:
  highlight: true
  html: true
  xhtmlOut: true
  breaks: true
  langPrefix:
  linkify: true
  typographer:
  quotes: “”‘’
  pre_class: highlight

swpp:
  # 是否启用插件
  enable: true
  # 是否在发布前自动执行脚本
  # auto_exec: true
  # 构建时拉取版本文件的警告等级，缺省为 1（该功能仅在 swpp-backends 版本号 >= 2.1.2 时可用）
  # 0 - 表示不允许出现 404 情况；1 - 表示允许服务器返回 404 状态码；2 - 表示允许任何 404（包括 DNS 解析失败等）
  # warn_level: 1
  # 检查版本的 URL，不能以 '/' 结尾
  # npm_url: 'https://registry.npmmirror.com'

# 配置谷歌、必应、百度链接主动推送
hexo_submit_urls_to_search_engine:
  submit_condition: count #链接被提交的条件，可选值：count | period 现仅支持count
  count: 9999 # 提交最新的10个链接
  period: 900 # 提交修改时间在 900 秒内的链接
  google: 1 # 是否向Google提交，可选值：1 | 0（0：否；1：是）
  bing: 1 # 是否向bing提交，可选值：1 | 0（0：否；1：是）
  baidu: 1 # 是否向baidu提交，可选值：1 | 0（0：否；1：是）
  txt_path: submit_urls.txt ## 文本文档名， 需要推送的链接会保存在此文本文档里
  baidu_host: https://gal.saop.cc ## 在百度站长平台中注册的域名
  baidu_token: QKccCqWGN1Sw5ERH ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  bing_host: https://gal.saop.cc ## 在bing站长平台中注册的域名
  bing_token: 02add63696134a489768d9316190ad31 ## 请注意这是您的秘钥， 所以请不要把它直接发布在公众仓库里!
  google_host: https://gal.saop.cc ## 在google站长平台中注册的域名
  google_key_file: Project.json #存放google key的json文件，放于网站根目录（与hexo _config.yml文件位置相同），请不要把json文件内容直接发布在公众仓库里!
  google_proxy: http://127.0.0.1:7897 # 向谷歌提交网址所使用的系统 http 代理，填 0 不使用
  replace: 0 # 是否替换链接中的部分字符串，可选值：1 | 0（0：否；1：是）
  find_what: https://gal.saop.cc
  replace_with: https://gal.saop.cc

# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  enable: true
  appId: "vbCGmPiCS9NAXT2yal0F0p3j-MdYXbMMI"
  appKey: "gnlLEqqCkWSemGVukyByZfu5"
  serverURLs: "https://valine.mikuhitori.xyz"
  placeholder: "昵称栏输入 QQ 号即可获取头像与邮箱..\n评论支持标准的 Markdown 全语法~"
  avatar_cdn: "https://weavatar.com/avatar/"
  pageSize: 20
  visitor: false
  comment_count: false # If false, comment count will only be displayed in post page, not in home page
  highlight: true
  recordIP: true
  emojiCDN: "//twikoo-magic.oss-cn-hangzhou.aliyuncs.com/"
  emojiMaps:
    {
      "QQ-OK": "QQ/OK.gif",
      "QQ-aini": "QQ/aini.gif",
      "QQ-aixin": "QQ/aixin.gif",
      "QQ-aoman": "QQ/aoman.gif",
      "QQ-baiyan": "QQ/baiyan.gif",
      "QQ-bangbangtang": "QQ/bangbangtang.gif",
      "QQ-baojin": "QQ/baojin.gif",
      "QQ-baoquan": "QQ/baoquan.gif",
      "QQ-bishi": "QQ/bishi.gif",
      "QQ-bizui": "QQ/bizui.gif",
      "QQ-cahan": "QQ/cahan.gif",
      "QQ-caidao": "QQ/caidao.gif",
      "QQ-chi": "QQ/chi.gif",
      "QQ-ciya": "QQ/ciya.gif",
      "QQ-dabing": "QQ/dabing.gif",
      "QQ-daku": "QQ/daku.gif",
      "QQ-dan": "QQ/dan.gif",
      "QQ-deyi": "QQ/deyi.gif",
      "QQ-doge": "QQ/doge.gif",
      "QQ-fadai": "QQ/fadai.gif",
      "QQ-fanu": "QQ/fanu.gif",
      "QQ-fendou": "QQ/fendou.gif",
      "QQ-ganga": "QQ/ganga.gif",
      "QQ-gouyin": "QQ/gouyin.gif",
      "QQ-guzhang": "QQ/guzhang.gif",
      "QQ-haixiu": "QQ/haixiu.gif",
      "QQ-hanxiao": "QQ/hanxiao.gif",
      "QQ-haobang": "QQ/haobang.gif",
      "QQ-haqian": "QQ/haqian.gif",
      "QQ-hecai": "QQ/hecai.gif",
      "QQ-hexie": "QQ/hexie.gif",
      "QQ-huaixiao": "QQ/huaixiao.gif",
      "QQ-jie": "QQ/jie.gif",
      "QQ-jingkong": "QQ/jingkong.gif",
      "QQ-jingxi": "QQ/jingxi.gif",
      "QQ-jingya": "QQ/jingya.gif",
      "QQ-juhua": "QQ/juhua.gif",
      "QQ-keai": "QQ/keai.gif",
      "QQ-kelian": "QQ/kelian.gif",
      "QQ-koubi": "QQ/koubi.gif",
      "QQ-ku": "QQ/ku.gif",
      "QQ-kuaikule": "QQ/kuaikule.gif",
      "QQ-kulou": "QQ/kulou.gif",
      "QQ-kun": "QQ/kun.gif",
      "QQ-lanqiu": "QQ/lanqiu.gif",
      "QQ-leiben": "QQ/leiben.gif",
      "QQ-lenghan": "QQ/lenghan.gif",
      "QQ-liuhan": "QQ/liuhan.gif",
      "QQ-liulei": "QQ/liulei.gif",
      "QQ-nanguo": "QQ/nanguo.gif",
      "QQ-penxue": "QQ/penxue.gif",
      "QQ-piezui": "QQ/piezui.gif",
      "QQ-pijiu": "QQ/pijiu.gif",
      "QQ-qiang": "QQ/qiang.gif",
      "QQ-qiaoda": "QQ/qiaoda.gif",
      "QQ-qinqin": "QQ/qinqin.gif",
      "QQ-qiudale": "QQ/qiudale.gif",
      "QQ-quantou": "QQ/quantou.gif",
      "QQ-saorao": "QQ/saorao.gif",
      "QQ-se": "QQ/se.gif",
      "QQ-shengli": "QQ/shengli.gif",
      "QQ-shouqiang": "QQ/shouqiang.gif",
      "QQ-shuai": "QQ/shuai.gif",
      "QQ-shui": "QQ/shui.gif",
      "QQ-tiaopi": "QQ/tiaopi.gif",
      "QQ-touxiao": "QQ/touxiao.gif",
      "QQ-tu": "QQ/tu.gif",
      "QQ-tuosai": "QQ/tuosai.gif",
      "QQ-weiqu": "QQ/weiqu.gif",
      "QQ-weixiao": "QQ/weixiao.gif",
      "QQ-woshou": "QQ/woshou.gif",
      "QQ-wozuimei": "QQ/wozuimei.gif",
      "QQ-wunai": "QQ/wunai.gif",
      "QQ-xia": "QQ/xia.gif",
      "QQ-xiaojiujie": "QQ/xiaojiujie.gif",
      "QQ-xiaoku": "QQ/xiaoku.gif",
      "QQ-xiaoyanger": "QQ/xiaoyanger.gif",
      "QQ-xieyanxiao": "QQ/xieyanxiao.gif",
      "QQ-xigua": "QQ/xigua.gif",
      "QQ-xu": "QQ/xu.gif",
      "QQ-yangtuo": "QQ/yangtuo.gif",
      "QQ-yinxian": "QQ/yinxian.gif",
      "QQ-yiwen": "QQ/yiwen.gif",
      "QQ-youhengheng": "QQ/youhengheng.gif",
      "QQ-youling": "QQ/youling.gif",
      "QQ-yun": "QQ/yun.gif",
      "QQ-zaijian": "QQ/zaijian.gif",
      "QQ-zhayanjian": "QQ/zhayanjian.gif",
      "QQ-zhemo": "QQ/zhemo.gif",
      "QQ-zhouma": "QQ/zhouma.gif",
      "QQ-zhuakuang": "QQ/zhuakuang.gif",
      "QQ-zuohengheng": "QQ/zuohengheng.gif",
      "贴吧新表情-image_emoticon": "Tieba-New/image_emoticon.png",
      "贴吧新表情-image_emoticon10": "Tieba-New/image_emoticon10.png",
      "贴吧新表情-image_emoticon100": "Tieba-New/image_emoticon100.png",
      "贴吧新表情-image_emoticon101": "Tieba-New/image_emoticon101.png",
      "贴吧新表情-image_emoticon102": "Tieba-New/image_emoticon102.png",
      "贴吧新表情-image_emoticon103": "Tieba-New/image_emoticon103.png",
      "贴吧新表情-image_emoticon104": "Tieba-New/image_emoticon104.png",
      "贴吧新表情-image_emoticon105": "Tieba-New/image_emoticon105.png",
      "贴吧新表情-image_emoticon106": "Tieba-New/image_emoticon106.png",
      "贴吧新表情-image_emoticon107": "Tieba-New/image_emoticon107.png",
      "贴吧新表情-image_emoticon108": "Tieba-New/image_emoticon108.png",
      "贴吧新表情-image_emoticon109": "Tieba-New/image_emoticon109.png",
      "贴吧新表情-image_emoticon11": "Tieba-New/image_emoticon11.png",
      "贴吧新表情-image_emoticon110": "Tieba-New/image_emoticon110.png",
      "贴吧新表情-image_emoticon111": "Tieba-New/image_emoticon111.png",
      "贴吧新表情-image_emoticon112": "Tieba-New/image_emoticon112.png",
      "贴吧新表情-image_emoticon113": "Tieba-New/image_emoticon113.png",
      "贴吧新表情-image_emoticon114": "Tieba-New/image_emoticon114.png",
      "贴吧新表情-image_emoticon115": "Tieba-New/image_emoticon115.png",
      "贴吧新表情-image_emoticon116": "Tieba-New/image_emoticon116.png",
      "贴吧新表情-image_emoticon117": "Tieba-New/image_emoticon117.png",
      "贴吧新表情-image_emoticon118": "Tieba-New/image_emoticon118.png",
      "贴吧新表情-image_emoticon119": "Tieba-New/image_emoticon119.png",
      "贴吧新表情-image_emoticon12": "Tieba-New/image_emoticon12.png",
      "贴吧新表情-image_emoticon120": "Tieba-New/image_emoticon120.png",
      "贴吧新表情-image_emoticon121": "Tieba-New/image_emoticon121.png",
      "贴吧新表情-image_emoticon122": "Tieba-New/image_emoticon122.png",
      "贴吧新表情-image_emoticon123": "Tieba-New/image_emoticon123.png",
      "贴吧新表情-image_emoticon124": "Tieba-New/image_emoticon124.png",
      "贴吧新表情-image_emoticon13": "Tieba-New/image_emoticon13.png",
      "贴吧新表情-image_emoticon14": "Tieba-New/image_emoticon14.png",
      "贴吧新表情-image_emoticon15": "Tieba-New/image_emoticon15.png",
      "贴吧新表情-image_emoticon16": "Tieba-New/image_emoticon16.png",
      "贴吧新表情-image_emoticon17": "Tieba-New/image_emoticon17.png",
      "贴吧新表情-image_emoticon18": "Tieba-New/image_emoticon18.png",
      "贴吧新表情-image_emoticon19": "Tieba-New/image_emoticon19.png",
      "贴吧新表情-image_emoticon2": "Tieba-New/image_emoticon2.png",
      "贴吧新表情-image_emoticon20": "Tieba-New/image_emoticon20.png",
      "贴吧新表情-image_emoticon21": "Tieba-New/image_emoticon21.png",
      "贴吧新表情-image_emoticon22": "Tieba-New/image_emoticon22.png",
      "贴吧新表情-image_emoticon23": "Tieba-New/image_emoticon23.png",
      "贴吧新表情-image_emoticon24": "Tieba-New/image_emoticon24.png",
      "贴吧新表情-image_emoticon25": "Tieba-New/image_emoticon25.png",
      "贴吧新表情-image_emoticon26": "Tieba-New/image_emoticon26.png",
      "贴吧新表情-image_emoticon27": "Tieba-New/image_emoticon27.png",
      "贴吧新表情-image_emoticon28": "Tieba-New/image_emoticon28.png",
      "贴吧新表情-image_emoticon29": "Tieba-New/image_emoticon29.png",
      "贴吧新表情-image_emoticon3": "Tieba-New/image_emoticon3.png",
      "贴吧新表情-image_emoticon30": "Tieba-New/image_emoticon30.png",
      "贴吧新表情-image_emoticon31": "Tieba-New/image_emoticon31.png",
      "贴吧新表情-image_emoticon32": "Tieba-New/image_emoticon32.png",
      "贴吧新表情-image_emoticon33": "Tieba-New/image_emoticon33.png",
      "贴吧新表情-image_emoticon34": "Tieba-New/image_emoticon34.png",
      "贴吧新表情-image_emoticon35": "Tieba-New/image_emoticon35.png",
      "贴吧新表情-image_emoticon36": "Tieba-New/image_emoticon36.png",
      "贴吧新表情-image_emoticon37": "Tieba-New/image_emoticon37.png",
      "贴吧新表情-image_emoticon38": "Tieba-New/image_emoticon38.png",
      "贴吧新表情-image_emoticon39": "Tieba-New/image_emoticon39.png",
      "贴吧新表情-image_emoticon4": "Tieba-New/image_emoticon4.png",
      "贴吧新表情-image_emoticon40": "Tieba-New/image_emoticon40.png",
      "贴吧新表情-image_emoticon41": "Tieba-New/image_emoticon41.png",
      "贴吧新表情-image_emoticon42": "Tieba-New/image_emoticon42.png",
      "贴吧新表情-image_emoticon43": "Tieba-New/image_emoticon43.png",
      "贴吧新表情-image_emoticon44": "Tieba-New/image_emoticon44.png",
      "贴吧新表情-image_emoticon45": "Tieba-New/image_emoticon45.png",
      "贴吧新表情-image_emoticon46": "Tieba-New/image_emoticon46.png",
      "贴吧新表情-image_emoticon47": "Tieba-New/image_emoticon47.png",
      "贴吧新表情-image_emoticon48": "Tieba-New/image_emoticon48.png",
      "贴吧新表情-image_emoticon49": "Tieba-New/image_emoticon49.png",
      "贴吧新表情-image_emoticon5": "Tieba-New/image_emoticon5.png",
      "贴吧新表情-image_emoticon50": "Tieba-New/image_emoticon50.png",
      "贴吧新表情-image_emoticon6": "Tieba-New/image_emoticon6.png",
      "贴吧新表情-image_emoticon66": "Tieba-New/image_emoticon66.png",
      "贴吧新表情-image_emoticon67": "Tieba-New/image_emoticon67.png",
      "贴吧新表情-image_emoticon68": "Tieba-New/image_emoticon68.png",
      "贴吧新表情-image_emoticon69": "Tieba-New/image_emoticon69.png",
      "贴吧新表情-image_emoticon7": "Tieba-New/image_emoticon7.png",
      "贴吧新表情-image_emoticon70": "Tieba-New/image_emoticon70.png",
      "贴吧新表情-image_emoticon71": "Tieba-New/image_emoticon71.png",
      "贴吧新表情-image_emoticon72": "Tieba-New/image_emoticon72.png",
      "贴吧新表情-image_emoticon73": "Tieba-New/image_emoticon73.png",
      "贴吧新表情-image_emoticon74": "Tieba-New/image_emoticon74.png",
      "贴吧新表情-image_emoticon75": "Tieba-New/image_emoticon75.png",
      "贴吧新表情-image_emoticon76": "Tieba-New/image_emoticon76.png",
      "贴吧新表情-image_emoticon77": "Tieba-New/image_emoticon77.png",
      "贴吧新表情-image_emoticon78": "Tieba-New/image_emoticon78.png",
      "贴吧新表情-image_emoticon79": "Tieba-New/image_emoticon79.png",
      "贴吧新表情-image_emoticon8": "Tieba-New/image_emoticon8.png",
      "贴吧新表情-image_emoticon80": "Tieba-New/image_emoticon80.png",
      "贴吧新表情-image_emoticon81": "Tieba-New/image_emoticon81.png",
      "贴吧新表情-image_emoticon82": "Tieba-New/image_emoticon82.png",
      "贴吧新表情-image_emoticon83": "Tieba-New/image_emoticon83.png",
      "贴吧新表情-image_emoticon84": "Tieba-New/image_emoticon84.png",
      "贴吧新表情-image_emoticon85": "Tieba-New/image_emoticon85.png",
      "贴吧新表情-image_emoticon86": "Tieba-New/image_emoticon86.png",
      "贴吧新表情-image_emoticon87": "Tieba-New/image_emoticon87.png",
      "贴吧新表情-image_emoticon88": "Tieba-New/image_emoticon88.png",
      "贴吧新表情-image_emoticon89": "Tieba-New/image_emoticon89.png",
      "贴吧新表情-image_emoticon9": "Tieba-New/image_emoticon9.png",
      "贴吧新表情-image_emoticon90": "Tieba-New/image_emoticon90.png",
      "贴吧新表情-image_emoticon91": "Tieba-New/image_emoticon91.png",
      "贴吧新表情-image_emoticon92": "Tieba-New/image_emoticon92.png",
      "贴吧新表情-image_emoticon93": "Tieba-New/image_emoticon93.png",
      "贴吧新表情-image_emoticon94": "Tieba-New/image_emoticon94.png",
      "贴吧新表情-image_emoticon95": "Tieba-New/image_emoticon95.png",
      "贴吧新表情-image_emoticon96": "Tieba-New/image_emoticon96.png",
      "贴吧新表情-image_emoticon97": "Tieba-New/image_emoticon97.png",
      "贴吧新表情-image_emoticon98": "Tieba-New/image_emoticon98.png",
      "贴吧新表情-image_emoticon99": "Tieba-New/image_emoticon99.png",
    }
  enableQQ: true

fireworks:
  enable: true

all_minifier: true

image_minifier:
  enable: false
  interlaced: false
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  silent: false